### PR TITLE
Feature  main column tabs

### PR DESCRIPTION
**Pull request by karjac14**

### CODE REVIEW

**Comment by Ricecoder** [comment]
Interesting approach with the `.ready`. I'll have to look that up. Good work! :+1:

**Comment by s4dmw** [comment]
does `.this` work? i didnt think that was a function?

other than that it looks good :+1:

**Comment by karjac14** [comment]
thanks for the heads up!

**Comment by s4dmw** [comment]
:+1:

**Comment by cmauban** [comment]
looks good! :+1: remember, don't put spaces between `class=""` !

**Pull request merged**
